### ISSUE TITLE
Compile for another architecture than the host architecture

### ISSUE THREAD

**Issue by dinosaure** [dinosaure/esperanto#12]
We should be able to provide `x86_64` and `aarch64` at least.

**Comment by ingenieroariel** [comment]
Compiling for another architecture would be great, but I think just upgrading to latest Cosmopolitan would make the binary run on aarch64.

https://github.com/jart/cosmopolitan/commit/cd27a53345205b39ac7a30b4bc1f9bfd4a84840c

**Comment by dinosaure** [comment]
Thanks, it seems very interesting indeed. I will wait a new release of `cosmopolitan` and upgrade `esperanto` with this version :+1:.

**Comment by jart** [comment]
@dinosaure If you use Cosmopolitan at HEAD, it'll embed two copies of the Blink virtual machine inside your binary. One for Apple Arm64 and another for Linux Arm64. Your programs should *just work* on platforms like Macbook M1 and RasPi. See:

https://github.com/jart/cosmopolitan/blob/d484e1dbd4b8736ccc7f287fce28915afdfeb22d/ape/ape.S#L693-L779

If you encounter any issues, file one here: https://github.com/jart/blink Blink is designed for Cosmopolitan. The full suite of Cosmo's unit tests pass when running under it. Blink is able to JIT x86_64 code on aarch64 so it has acceptable performance while offering the full flexibility of the x86_64 ISA and Linux Kernel ABI in a tiny 200kb embeddable binary that's even smaller when gzipped and embedded automatically by APE. Enjoy!

**Comment by jart** [comment]
Would it help you if I cut a new release of Cosmopolitan that includes this new improvement?

**Comment by dinosaure** [comment]
> Would it help you if I cut a new release of Cosmopolitan that includes this new improvement?

As you want :+1: I can just upgrade artifacts on my side. Thanks for the explanation, so Cosmopolitan is **really** portable now 🎉 . Again, it's an impressive work! I let this issue open as long as I did not upgrade `esperanto`.

**Comment by jart** [comment]
I just uploaded fresh rolling release artifacts to https://justine.lol/cosmopolitan/download.html e.g. https://justine.lol/cosmopolitan/cosmopolitan.zip I intend to get a formal release out within the next 30 days. Cosmopolitan now offers you multiple dimensions of portability (in terms of the product of operating systems and architectures) which is something no C/C++ implementation has offered before as a singular implementation. You can think of it like Java, except you only have to pay for the virtual machine slowdown on non-x86 architectures, of which 11 are actually supported by Blink, except they're not included in APE by default because they don't have JIT (we only do JIT currently on amd64 and arm64). Glad you're enjoying it!

**Comment by dinosaure** [comment]
As far as I can say, the last release of Esperanto includes what is required to run an application on a `aarch64` CPU. So it's not a cross-compilation mechanism but a JIT transpilation from `x86_64` to `aarch64`. We probably can close this issue when `esperanto.0.0.4` has such support now. Thanks @jart for your work again.

**Comment by jart** [comment]
It's also worth mentioning that the Cosmopolitan repo has support for building native aarch64 binaries too now. So there's going to be multiple paths to supporting the architecture soon!
